version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-admin}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
